### ISSUE TITLE
hub complains about credentials with uwsgi

### ISSUE THREAD

**Issue by c-geek** [nijel/weblate#1122]
Hey,

We are using a weblate instance on our personal server, and get translations through pull requests.

This works very well with `hub` using command line interpreter. But when it comes to weblate using the "Push" button, we get credential errors.

We have the following configuration file for `uwsgi`:

```ini
[uwsgi]
uid           = weblate
gid           = weblate
plugins       = python
master        = true
#protocol      = uwsgi
socket        = 127.0.0.1:8000
env = PATH=/usr/local/bin:$(PATH)
home          = /opt/weblate/.virtualenvs/weblate
#unenv	      = HOME
wsgi-file     = /opt/weblate/app/weblate/wsgi.py
python-path   = /opt/weblate/app
# Needed for OAuth/OpenID
buffer-size   = 32768 
# Increase number of workers for heavily loaded sites
#workers       = 6
# Needed for background processing
enable-threads = true
# Child processes do not need file descriptors
close-on-exec = true
```

The `hub` credentials were initially stored by `hub` at `/opt/weblate/.config/hub`, since the `weblate` user home is ``/opt/weblate/`. I tried to copy it to `/opt/weblate/.virtualenvs/weblate/.config/hub` as well. But I always get the following logs in weblate:

```
ERROR ucoin-blog/blog-home: failed to push on repo: $ git config alias.push
$ git push dunibot master:master
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists. (128)
```

Again, this works using command line interpreter under `weblate` user.

Thanks for your eventual help!

**Comment by nijel** [comment]
I think copying the configuration to Weblate data dir into home folder should help.

**Comment by c-geek** [comment]
Ok thank you, maybe this wasn't the real problem but you lead me to a road where I could see we had 2 `data/vcs` folders:

* `/opt/weblate/app/data/vcs` (the good one)
* `/opt/weblate/app/weblate/data/vcs` (the wrong one)

We have such a structure because of a server migration ([software name change](https://duniter.org/ucoin-rename-duniter/)). So not only we made some backups, but the GitHub repositories changed of owner, so the repostories URI changed as well.

Also I blindly kept trying to `hub push` thinking it used the hub credentials [whereas it does not use it](https://github.com/github/hub/issues/580#issuecomment-46166546). So putting the SSH key + configuring the Components to the new GitHub URI made the job.

Finally, I've put the following line in `vcs.py`:

```python
self.push_to_fork(self.branch, self.branch)
```

... as I remember I already made such a fix [few times ago](https://github.com/nijel/weblate/pull/762).

Hope all this tips might help someone one day.

Thanks for your help and your work!

Cheers.

**Comment by nijel** [comment]
I've said you there to complain if adding -f was not enough ;-). Anyway that should be fixed now.

**Comment by c-geek** [comment]
Yes but I still don't know if that's not enough! Probably if it was not other users would have complained. But I prefer to take this precaution :smile:

**Comment by nijel** [comment]
Okay, the problem is that nobody else probably used hub so far (see also #1010).
