### ISSUE TITLE
Same translation check ignored

### ISSUE THREAD

**Issue by crisp2u** [nijel/weblate#1261]
### Steps to reproduce
1.Add a new component with Java Property Strings UTF-8 from GIT
2.Set source language as NL
3.Add english translations almost identical as NL (out of 381 lines diff reports 87 changed)

### Actual behaviour
Weblate displays 99.6% strings translated

### Expected behaviour
Should identify identical translations and report them.

![image](https://cloud.githubusercontent.com/assets/651414/19704653/2978feb6-9b11-11e6-89d8-739686c88859.png)

### Server configuration
It's weblate 2.8 (just upgraded from 2.6) running inside docker container. Other components seem to work correct
 
output of command `./manage.py list_versions` 
 * Weblate 2.8
 * Python 2.7.9
 * Django 1.9.10
 * six 1.10.0
 * python-social-auth 0.2.19
 * Translate Toolkit 2.0.0b6
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.4.0
 * django-crispy-forms 1.6.0
 * compressor 1.6
 * djangorestframework 3.3.3
 * pytz 2016.7
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * Mercurial 3.8.3
 * Database backends: django.db.backends.postgresql_psycopg2

Thanks for any ideas.

**Comment by nijel** [comment]
Fixed in Git, thanks for spotting. The check did allow no change translation to English from times when there was no option to specify source language.

**Comment by crisp2u** [comment]
How do I force weblate to recheck the component ? I just updated to master from githib and I still see the same thing.

**Comment by nijel** [comment]
Use updatechecks management command
