### ISSUE TITLE
escaping does not work on multiline strings (android) [$15]

### ISSUE THREAD

**Issue by ruleant** [nijel/weblate#517]
Special characters (', ", <, >) and newlines (\n) are not escaped in a multi-line string.
In [this commit](https://github.com/ruleant/getback_gps/commit/40ca02d31f1d2fe90ce7c24e6c38491ecc8699db#diff-1673efb4e556521d93d62e6dd0a6fbe9) string `license` is added by Weblate, but the `'` characters are not escaped, like in fe. the `copyright` string.

In [this commit](https://github.com/ruleant/getback_gps/commit/42a539c8f730328528164fd2a35ce36d195b09ca) the faulty special characters are escaped manually, the newline characters `\n` are added manually as well.

**Comment by nijel** [comment]
I hope this has been fixed by merging @lukakama PR to translate-toolkit...

**Comment by nijel** [comment]
BTW: @lukakama , I think  you can claim the $15 bounty on this issue ;-).

**Comment by paour** [comment]
As I wrote on BountySource, the issue remains with the following versions:

 * Weblate weblate-2.8
 * Python 2.7.9
 * Django 1.9
 * six 1.10.0
 * python-social-auth 0.2.19
 * Translate Toolkit 2.0.0b4
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.6.4
 * django-crispy-forms 1.6.0
 * compressor 2.1
 * djangorestframework 3.4.6
 * pytz 2016.6.1
 * pyuca N/A
 * pyLibravatar N/A
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
@paour Sorry to hear that, I somehow assumed that it's really fixed when nobody complained for past year :-).

Anyway this is still something what needs to be addressed at translate-toolkit side. However I've just tried to test it (test added in https://github.com/nijel/translate/commit/2706bc1d23d986cbe869e7f4ecc9e2c0ab5ad219) and it seems to work according to my expectations...

**Comment by paour** [comment]
This test doesn't contain embedded markup (`<b>`), which I thought you mentioned was the source of some of the issues.

Because upgrading TT is pretty fraught, I haven't been able to keep up with versions as closely as I would have liked, and have gotten into the habit of manually fixing the strings, sorry, I know how frustrating it is when QA doesn't quickly validate fixes…

**Comment by nijel** [comment]
I've added test with markup and that one seems to work according to my expectations as well: https://github.com/translate/translate/commit/ddeaa2236b2a2ee7106fdc4bc35f09f348e2ce42
