### ISSUE TITLE
Save translation causes template error

### ISSUE THREAD

**Issue by Ninerian** [nijel/weblate#627]
I installed weblate to openshift. I'm a beginner to this tool, and also the workflow. Actually I managed to get the repo initialized and all languages are shown. But when I try to save an translation string the following error is logged:

```
ERROR:django.request:Internal Server Error: /projects/tourplayer/web-ui/de/translate/
[Thu Dec 18 05:48:34 2014] [error] Traceback (most recent call last):
[Thu Dec 18 05:48:34 2014] [error]   File "/var/lib/openshift/54914eb9e0b8cd71b90000ab/python/virtenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
[Thu Dec 18 05:48:34 2014] [error]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Thu Dec 18 05:48:34 2014] [error]   File "/var/lib/openshift/54914eb9e0b8cd71b90000ab/python/virtenv/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
[Thu Dec 18 05:48:34 2014] [error]     return func(*args, **kwargs)
[Thu Dec 18 05:48:34 2014] [error]   File "/var/lib/openshift/54914eb9e0b8cd71b90000ab/app-root/runtime/repo/weblate/trans/views/edit.py", line 517, in translate
[Thu Dec 18 05:48:34 2014] [error]     this_unit_url, next_unit_url
[Thu Dec 18 05:48:34 2014] [error]   File "/var/lib/openshift/54914eb9e0b8cd71b90000ab/app-root/runtime/repo/weblate/trans/views/edit.py", line 312, in handle_translate
[Thu Dec 18 05:48:34 2014] [error]     go_next = perform_translation(unit, form, request)
[Thu Dec 18 05:48:34 2014] [error]   File "/var/lib/openshift/54914eb9e0b8cd71b90000ab/app-root/runtime/repo/weblate/trans/views/edit.py", line 231, in perform_translation
[Thu Dec 18 05:48:34 2014] [error]     form.cleaned_data['fuzzy']
[Thu Dec 18 05:48:34 2014] [error]   File "/var/lib/openshift/54914eb9e0b8cd71b90000ab/app-root/runtime/repo/weblate/trans/models/unit.py", line 966, in translate
[Thu Dec 18 05:48:34 2014] [error]     saved = self.save_backend(request)
[Thu Dec 18 05:48:34 2014] [error]   File "/var/lib/openshift/54914eb9e0b8cd71b90000ab/app-root/runtime/repo/weblate/trans/models/unit.py", line 528, in save_backend
[Thu Dec 18 05:48:34 2014] [error]     (saved, pounit) = self.translation.update_unit(self, request, user)
[Thu Dec 18 05:48:34 2014] [error]   File "/var/lib/openshift/54914eb9e0b8cd71b90000ab/app-root/runtime/repo/weblate/trans/models/translation.py", line 843, in update_unit
[Thu Dec 18 05:48:34 2014] [error]     pounit, add = self.store.find_unit(unit.context, src)
[Thu Dec 18 05:48:34 2014] [error]   File "/var/lib/openshift/54914eb9e0b8cd71b90000ab/app-root/runtime/repo/weblate/trans/formats.py", line 480, in find_unit
[Thu Dec 18 05:48:34 2014] [error]     return self._find_unit_template(context)
[Thu Dec 18 05:48:34 2014] [error]   File "/var/lib/openshift/54914eb9e0b8cd71b90000ab/app-root/runtime/repo/weblate/trans/formats.py", line 850, in _find_unit_template
[Thu Dec 18 05:48:34 2014] [error]     '.' + context
[Thu Dec 18 05:48:34 2014] [error]   File "/var/lib/openshift/54914eb9e0b8cd71b90000ab/app-root/runtime/repo/weblate/trans/formats.py", line 447, in _find_unit_template
[Thu Dec 18 05:48:34 2014] [error]     'Could not find template unit for new unit!'
[Thu Dec 18 05:48:34 2014] [error] Exception: Could not find template unit for new unit!
```

I use JSON Files to manage my translation. They are structured like:
languages/de/web-ui.json

I also checked, if there are missing or wrong written keywords, but there aren't any.

**Comment by nijel** [comment]
What Weblateversion do you use? Similar issue has been fixed in fcbfbb43a4c5620fc15b1ddf99b486f2a8b8a40f.

**Comment by nijel** [comment]
Closing for now as I believe that fcbfbb4 has fixed this issue. Please reopen if the issue still exists.

**Comment by Ninerian** [comment]
Sorry was busy and couldn't answer. I updated to the latest version Weblate 2.2, but the error still occurs.

**Comment by nijel** [comment]
Okay, the problem is that there are more ways to use JSON for translating. What currently works fine in Weblate is simple format (see https://github.com/nijel/weblate-test/blob/master/json/cs.json), but more complex formats fail (eg. https://github.com/FelisCatus/SwitchyOmega/blob/master/omega-i18n/en/messages.json).

**Comment by nijel** [comment]
@Ninerian How does your json files look like?

**Comment by nijel** [comment]
For using more complex JSON translations than just key:value mappings, more support from translate-toolkit is needed, I've documented this in 4c8e679.

**Comment by nijel** [comment]
There were some issues in handing simple JSON files as well, but those should be fixed in 82840a3.

**Comment by nijel** [comment]
Closing for now as I believe the original issue has been caused by bugs fixed in 82840a3. I've created separate issue for Chrome JSON translations.
