### ISSUE TITLE
other translation warning in monolingual po files

### ISSUE THREAD

**Issue by paulpach** [nijel/weblate#658]
Suppose I have 2 sets of monolingual po files in 2 subprojects:

ItemNames.pot
en/ItemNames.po  (source)
es/ItemNames.po
...

ItemDescriptions.pot
en/ItemDescriptions.po  (source)
es/ItemDescriptions.po
...

Both set of files use the same keys,  one is for item names and the other one for descriptions.  Although the msgid is the same,  the source is different in each set.

Weblate is showing a warning for each unit saying that there is another translation for them.  If the source is different in monolingual it should not say that there is another translation for it, even if the key is the same.

**Comment by nijel** [comment]
How is your translation configured? Also can you share one of the files, so that I can try to reproduce this?

**Comment by paulpach** [comment]
Here is one:
http://weblate-blockstory.rhcloud.com/projects/block-story/itemnames/es/
(lots of warnings of different translations)
config:
[image: Inline image 2]


Here is the other:
http://weblate-blockstory.rhcloud.com/projects/block-story/items/es/
(mostly ok).
config:
[image: Inline image 1]

You can download the sources from there.


here is a warning that should not be there:

http://weblate-blockstory.rhcloud.com/projects/block-story/itemnames/es/translate/?type=inconsistent

**Comment by paulpach** [comment]
Here is a better link,  this one says there is other translation available:

http://weblate-blockstory.rhcloud.com/projects/block-story/items/es/translate/?checksum=e16aadf94681c0f97fa7a25d37e3c8c9

which is not true.

**Comment by nijel** [comment]
Indeed there was bug in matching same units, fixed in git.

**Comment by paulpach** [comment]
You Rock nijel,  tx.

**Comment by paulpach** [comment]
I updated and tried,  the duplicate message disappeared,  but I am still getting an "inconsistent" warning. see this one:

http://weblate-blockstory.rhcloud.com/projects/block-story/itemnames/es/translate/?checksum=7c656094191b954af3beddf67711d90c

**Comment by paulpach** [comment]
nvm,  I needed to run 
python updatechecks --all 

works great now,  tx.

**Comment by nijel** [comment]
Yes, I forgot to mention that you need to update checks for this to be effective...
